name: Chromium Tarball Generation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Chromium version
        required: true

jobs:
  generate-tarball:
    runs-on: ubuntu-latest

    steps:
      - name: Free up space on the runner
        run: |
          echo Before:
          df -m .
          sudo rm -rf \
            /usr/local/.ghcup \
            /usr/local/lib/android \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift \
            "$AGENT_TOOLSDIRECTORY"
          echo After:
          df -m .

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Chromium Bot"
          git config --global user.email "chromium@gentoo.org"

      - name: Package Chromium tarballs for ${{ inputs.version || github.ref_name }}
        run: ./package_chromium.sh ${{ inputs.version || github.ref_name }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: build-artifacts
            path: out/

      - name: Notify success
        if: success() && github.event_name == 'push'
        uses: Gottox/irc-message-action@v2.1.3
        with:
          server: irc.libera.chat
          notice: false
          channel: "#gentoo-chromium"
          nickname: chromium-notifs
          message: "Successfully generated Chromium tarballs for ${{ github.ref_name }}"

      - name: Notify failure
        if: failure() && github.event_name == 'push'
        uses: Gottox/irc-message-action@v2.1.3
        with:
          server: irc.libera.chat
          notice: false
          channel: "#gentoo-chromium"
          nickname: chromium-notifs
          message: "Failed to generate Chromium tarballs for ${{ github.ref_name }}"

  upload-tarball:
    runs-on: ubuntu-latest

    needs: generate-tarball

    container:
      image: gentoo/stage3:nomultilib

    steps:
      - name: Install dependencies
        run: >
          emerge-webrsync && getuto &&
          emerge --getbinpkg s3cmd

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
            name: build-artifacts

      - name: Upload tarballs to S3
        run: |
          s3cmd --host=syd1.digitaloceanspaces.com \
          --host-bucket='%(bucket)s.syd1.digitaloceanspaces.com' \
          --access_key=${{ secrets.S3_ACCESS_KEY }} \
          --secret_key=${{ secrets.S3_SECRET_KEY }} \
          put out/*.tar.xz* s3://${{ vars.S3_BUCKET }}/

      - name: Notify success
        if: success()
        uses: Gottox/irc-message-action@v2.1.5
        with:
          server: irc.libera.chat
          notice: false
          channel: "#gentoo-chromium"
          nickname: chromium-notifs
          message: "Successfully uploaded Chromium tarballs for ${{ github.ref_name }}"

      - name: Notify failure
        if: failure()
        uses: Gottox/irc-message-action@v2.1.5
        with:
          server: irc.libera.chat
          notice: false
          channel: "#gentoo-chromium"
          nickname: chromium-notifs
          message: "Failed to upload Chromium tarballs for ${{ github.ref_name }}"
